"""
Write src/art3d/catalog.ts from the build manifests (assets-src/out/manifest/*.json, one per built model, with the
measured footprint, nodes, materials and triangles) and the hand-kept metadata below (names, kinds, styles, which
clip a seat uses, which Look colour tints which material).

    python assets-src/catalog_gen.py

The floor engine reads models only through this catalogue, so it never guesses a file, a node or a material name.
"""
import json
import os

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
MAN = os.path.join(HERE, 'out', 'manifest')
OUT = os.path.join(ROOT, 'src', 'art3d', 'catalog.ts')

# people.ts Outfit fields (main, second, pants, shoes) or fixed colours, per material, per outfit.
OUTFIT_TINTS = {
    'dress': {'Top': 'main', 'Detail': 'second', 'Shoes': 'shoes'},
    'jumper': {'Top': 'main', 'Bottom': 'pants', 'Shoes': 'shoes'},
    'dungarees': {'Top': 'main', 'Bottom': 'pants', 'Detail': '#f3d27a', 'Shoes': 'shoes'},
    'suit': {'Top': 'main', 'Bottom': 'pants', 'Shirt': '#fbf8f6', 'Detail': 'second', 'Shoes': 'shoes'},
    'hoodie': {'Top': 'main', 'Bottom': 'pants', 'Shirt': '#ffffff', 'Shoes': 'shoes'},
    'sporty': {'Top': 'main', 'Bottom': 'pants', 'Detail': 'second', 'Shoes': 'shoes'},
    'cardigan': {'Top': 'main', 'Shirt': 'second', 'Bottom': 'pants', 'Detail': 'main+', 'Shoes': 'shoes'},
    'jacket': {'Top': 'main', 'Shirt': 'second', 'Bottom': 'pants', 'Shoes': 'shoes'},
    'scrubs': {'Scrubs': 'main', 'Shoes': 'shoes'},
    'chef': {'Top': 'main', 'Detail': 'second', 'Shirt': '#a096a0', 'Bottom': 'pants', 'Shoes': 'shoes'},
    'player': {'Top': 'main', 'Apron': 'second', 'Bottom': 'pants', 'Shoes': 'shoes'},
}

HAIR = ['long', 'bob', 'bun', 'curly', 'crop', 'ponytail', 'braids']


def ts(v, ind=0):
    """A Python value as TypeScript source (keys unquoted when they can be)."""
    pad = '  ' * ind
    if isinstance(v, dict):
        if not v:
            return '{}'
        items = []
        for k, x in v.items():
            key = k if (k.replace('_', 'a').isalnum() and not k[0].isdigit()) else json.dumps(k)
            items.append(f'{pad}  {key}: {ts(x, ind + 1)}')
        return '{\n' + ',\n'.join(items) + f',\n{pad}}}'
    if isinstance(v, list):
        inner = [ts(x, ind + 1) for x in v]
        one = '[' + ', '.join(inner) + ']'
        if len(one) < 110 and '\n' not in one:
            return one
        return '[\n' + ',\n'.join(f'{pad}  {x}' for x in inner) + f',\n{pad}]'
    if isinstance(v, bool):
        return 'true' if v else 'false'
    if v is None:
        return 'null'
    if isinstance(v, float):
        return repr(round(v, 4))
    return json.dumps(v)


def load(name):
    p = os.path.join(MAN, name)
    return json.load(open(p)) if os.path.exists(p) else None


def people():
    fem, masc = load('people_fem.json'), load('people_masc.json')
    kinds = {k: m for k, m in (('fem', fem), ('masc', masc)) if m}
    out = {
        'files': {k: m['file'] for k, m in kinds.items()},
        'bones': (fem or masc)['bones'],
        'height': {k: m['height'] for k, m in kinds.items()},
        'walkSpeed': {k: m['walkSpeed'] for k, m in kinds.items()},
        'outfits': {k: sorted(n[len('outfit_'):] for n in m['meshes'] if n.startswith('outfit_')) for k, m in kinds.items()},
        'outfitTints': OUTFIT_TINTS,
        'always': ['head_<kind>', 'eyes', 'brows'],
        'hair': HAIR,
        'accessories': {'1': 'bow_<hair>', '2': 'glasses', '3': 'flower_<hair>'},
        'tints': {'Skin': 'SKIN[look.skin].base (multiplies the face and body texture)', 'Hair': 'HAIR[look.hair].base (multiplies the strand texture)',
                  'Brows': 'HAIR[look.hair].dark', 'Eyes': 'the iris colour (people.ts irisForSeed or IRIS); EyeWhite stays',
                  'Accessory': 'OUTFIT[(look.outfit + 5) % 8]', 'fixed': ['EyeWhite', 'EyeShine', 'Lashes', 'Sole', 'Glasses', 'Lens', 'FlowerCentre']},
        'animations': sorted((fem or masc)['clips']),
        'clipSeconds': (fem or masc)['clips'],
        'seatedClips': ['sit_chair', 'sit_sofa', 'sit_stool', 'sit_pedicure', 'sleepy'],
        'tris': {k: {n: d['tris'] for n, d in m['meshes'].items()} for k, m in kinds.items()},
    }
    seats = json.load(open(os.path.join(HERE, 'out', 'seats.json'))) if os.path.exists(os.path.join(HERE, 'out', 'seats.json')) else {}
    # For seats without a node (someone else's furniture): how far the hips sit above the floor the feet stand on.
    out['hipsAboveFeet'] = {k: round(-v['heel_z_min'], 3) for k, v in seats.items() if k != 'sit_chair'}
    return out


HEADER = '''/**
 * The 3D models' catalogue, generated by assets-src/catalog_gen.py from the Blender builds (do not edit by hand:
 * change the build or the generator, then run `python assets-src/catalog_gen.py`). The floor engine reads models
 * only through here, so it never guesses a file, a node or a material name. See docs/3D-ASSETS.md.
 *
 * Every file is glTF 2.0 binary under public/models/, Y up, metres, +Z the model's front, the origin on the floor in
 * the middle of the footprint, compressed with meshopt (gltfpack): load with GLTFLoader.setMeshoptDecoder.
 * Materials are flat PBR colours named by role; soft ambient occlusion is baked into the vertex colours (COLOR_0), so
 * keep `vertexColors` on when you tint (`material.color` multiplies it).
 */

/** A helper node in a model: where a seated person's hips go (and which way they face: the node's +Z), etc. */
export type NodeInfo = { pos: [number, number, number]; rotY: number }

/** One look of a purchasable item: its own file, or the default file with materials recoloured. */
export type ModelStyle = { id: string; name: string; file: string; materialOverrides?: Record<string, number>; thumb: string }

export type ModelKind = 'station' | 'front' | 'room' | 'plant' | 'life' | 'decor' | 'gift'

export type ModelEntry = {
  id: string
  name: string
  kind: ModelKind
  /** The default style's file, relative to public/models/. */
  file: string
  /** Width (x) and depth (z) in metres. */
  footprint: [number, number]
  height: number
  /** Helper nodes by name: seat, work, feet, tool, lookat (stations), and any others the item has. */
  nodes: Record<string, NodeInfo>
  /** Materials a decor set may tint (Accent, Trim). */
  recolour: string[]
  materials: string[]
  tris: number
  /** The clip a person plays on this item's seat node, if it has one. */
  sitClip?: string
  /** Animation clips inside the file (the cat). */
  animations?: string[]
  /** Ground speed (m/s) the in-place walk clip matches (the cat). */
  walkSpeed?: number
  /** For purchasable items: three styles (the first is the default). */
  styles?: ModelStyle[]
  /** The decor set or regular this item belongs to. */
  set?: string
  regular?: string
}

/**
 * The people: two bodies (fem, masc) on one 23-bone rig (Quaternius UAL naming), built on Quaternius' Universal Base
 * Characters (CC0). Each file holds every part: always show `always` (the head with its textured face, the eyes, the
 * brows), then one outfit mesh `outfit_<outfit>` (the body below the neck, dressed), one hair `hair_<style>` and at most
 * one accessory; hide the rest. Toggle `visible` on the part's named node (a child of the rig): its meshes, one per
 * material, hang under it, sometimes in an unnamed group.
 * - Tint by material name (`tints`): Skin, Hair and Brows multiply their textures; the outfit's materials follow
 *   people.ts `outfitOf` as `outfitTints` lists ('main', 'second', 'pants', 'shoes', a fixed colour, or 'main+' for a
 *   lighter main). Keep `vertexColors` on (the hair's soft occlusion is in COLOR_0).
 * - Hair: `hair[look.hairStyle]`. Accessories by Look.accessory: 1 bow, 2 glasses, 3 flower clip; `<hair>` is the
 *   hair style's name (each bow and flower sits on its own hair style's surface).
 * - Faces are Quaternius' sculpted faces (in the Skin texture on head_<kind>), with bigger, opened eyes. A customer's
 *   face differs by skin tone, eye colour (the Eyes material) and brow colour.
 * - Clips: `animations`. The seated ones (`seatedClips`) put the hips (pelvis joint) exactly on the model's origin,
 *   facing +Z: put the character's origin on a station's `seat` node with the node's rotation. For a seat with no
 *   node, `hipsAboveFeet` says how high the hips sit above the floor the feet rest on.
 * - `sit_down` / `stand_up` (0.6 s) go between standing in front of a sofa-height seat and `sit_sofa`; play them with
 *   the origin already on the seat node (the feet start `hipsAboveFeet.sit_sofa` below it), then loop the seated clip.
 * - `walkSpeed` is the ground speed (m/s) the in-place walk cycle matches at timeScale 1.
 */
'''


def main():
    ppl = people()
    models = []
    for name in sorted(os.listdir(MAN)) if os.path.isdir(MAN) else []:
        if name.startswith('people_'):
            continue
        m = json.load(open(os.path.join(MAN, name)))
        if 'kind' in m:
            models.append(m)
    models.sort(key=lambda m: (['station', 'front', 'room', 'plant', 'life', 'decor', 'gift'].index(m['kind']), m['id']))
    src = HEADER
    src += '\nexport const PEOPLE = ' + ts(ppl) + ' as const\n'
    src += '\nexport const MODELS: ModelEntry[] = ' + ts(models) + '\n'
    src += '\nexport const MODEL_BY_ID: Record<string, ModelEntry> = Object.fromEntries(MODELS.map(m => [m.id, m]))\n'
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, 'w', encoding='utf8', newline='\n') as f:
        f.write(src)
    print('wrote', OUT, len(models), 'models')


if __name__ == '__main__':
    main()
