/**
 * The 3D models' catalogue, generated by assets-src/catalog_gen.py from the Blender builds (do not edit by hand:
 * change the build or the generator, then run `python assets-src/catalog_gen.py`). The floor engine reads models
 * only through here, so it never guesses a file, a node or a material name. See docs/3D-ASSETS.md.
 *
 * Every file is glTF 2.0 binary under public/models/, Y up, metres, +Z the model's front, the origin on the floor in
 * the middle of the footprint, compressed with meshopt (gltfpack): load with GLTFLoader.setMeshoptDecoder.
 * Materials are flat PBR colours named by role; soft ambient occlusion is baked into the vertex colours (COLOR_0), so
 * keep `vertexColors` on when you tint (`material.color` multiplies it).
 */

/** A helper node in a model: where a seated person's hips go (and which way they face: the node's +Z), etc. */
export type NodeInfo = { pos: [number, number, number]; rotY: number }

/** One look of a purchasable item: its own file, or the default file with materials recoloured. */
export type ModelStyle = { id: string; name: string; file: string; materialOverrides?: Record<string, number>; thumb: string }

export type ModelKind = 'station' | 'front' | 'room' | 'plant' | 'life' | 'decor' | 'gift'

export type ModelEntry = {
  id: string
  name: string
  kind: ModelKind
  /** The default style's file, relative to public/models/. */
  file: string
  /** Width (x) and depth (z) in metres. */
  footprint: [number, number]
  height: number
  /** Helper nodes by name: seat, work, feet, tool, lookat (stations), and any others the item has. */
  nodes: Record<string, NodeInfo>
  /** Materials a decor set may tint (Accent, Trim). */
  recolour: string[]
  materials: string[]
  tris: number
  /** The clip a person plays on this item's seat node, if it has one. */
  sitClip?: string
  /** Animation clips inside the file (the cat). */
  animations?: string[]
  /** For purchasable items: three styles (the first is the default). */
  styles?: ModelStyle[]
  /** The decor set or regular this item belongs to. */
  set?: string
  regular?: string
}

/**
 * The people: two bodies (fem, masc) on one 23-bone rig (Quaternius UAL naming), built on Quaternius' Universal Base
 * Characters (CC0). Each file holds every part: always show `always` (the head with its textured face, the eyes, the
 * brows), then one outfit mesh `outfit_<outfit>` (the body below the neck, dressed), one hair `hair_<style>` and at most
 * one accessory; hide the rest. Toggle `visible` on the part's named node (a child of the rig): its meshes, one per
 * material, hang under it, sometimes in an unnamed group.
 * - Tint by material name (`tints`): Skin, Hair and Brows multiply their textures; the outfit's materials follow
 *   people.ts `outfitOf` as `outfitTints` lists ('main', 'second', 'pants', 'shoes', a fixed colour, or 'main+' for a
 *   lighter main). Keep `vertexColors` on (the hair's soft occlusion is in COLOR_0).
 * - Hair: `hair[look.hairStyle]`. Accessories by Look.accessory: 1 bow, 2 glasses, 3 flower clip; `<hair>` is the
 *   hair style's name (each bow and flower sits on its own hair style's surface).
 * - Faces are Quaternius' sculpted faces (in the Skin texture on head_<kind>), with bigger, opened eyes. A customer's
 *   face differs by skin tone, eye colour (the Eyes material) and brow colour.
 * - Clips: `animations`. The seated ones (`seatedClips`) put the hips (pelvis joint) exactly on the model's origin,
 *   facing +Z: put the character's origin on a station's `seat` node with the node's rotation. For a seat with no
 *   node, `hipsAboveFeet` says how high the hips sit above the floor the feet rest on.
 * - `walkSpeed` is the ground speed (m/s) the in-place walk cycle matches at timeScale 1.
 */

export const PEOPLE = {
  files: {
    fem: "people/fem.glb",
    masc: "people/masc.glb",
  },
  bones: [
    "root",
    "pelvis",
    "spine_01",
    "spine_02",
    "spine_03",
    "neck_01",
    "Head",
    "clavicle_l",
    "upperarm_l",
    "lowerarm_l",
    "hand_l",
    "clavicle_r",
    "upperarm_r",
    "lowerarm_r",
    "hand_r",
    "thigh_l",
    "calf_l",
    "foot_l",
    "ball_l",
    "thigh_r",
    "calf_r",
    "foot_r",
    "ball_r",
  ],
  height: {
    fem: 1.673,
    masc: 1.709,
  },
  walkSpeed: {
    fem: 0.676,
    masc: 0.715,
  },
  outfits: {
    fem: [
      "cardigan",
      "chef",
      "dress",
      "dungarees",
      "hoodie",
      "jacket",
      "jumper",
      "player",
      "scrubs",
      "sporty",
      "suit",
    ],
    masc: ["cardigan", "chef", "dungarees", "hoodie", "jacket", "jumper", "player", "scrubs", "sporty", "suit"],
  },
  outfitTints: {
    dress: {
      Top: "main",
      Detail: "second",
      Shoes: "shoes",
    },
    jumper: {
      Top: "main",
      Bottom: "pants",
      Shoes: "shoes",
    },
    dungarees: {
      Top: "main",
      Bottom: "pants",
      Detail: "#f3d27a",
      Shoes: "shoes",
    },
    suit: {
      Top: "main",
      Bottom: "pants",
      Shirt: "#fbf8f6",
      Detail: "second",
      Shoes: "shoes",
    },
    hoodie: {
      Top: "main",
      Bottom: "pants",
      Shirt: "#ffffff",
      Shoes: "shoes",
    },
    sporty: {
      Top: "main",
      Bottom: "pants",
      Detail: "second",
      Shoes: "shoes",
    },
    cardigan: {
      Top: "main",
      Shirt: "second",
      Bottom: "pants",
      Detail: "main+",
      Shoes: "shoes",
    },
    jacket: {
      Top: "main",
      Shirt: "second",
      Bottom: "pants",
      Shoes: "shoes",
    },
    scrubs: {
      Scrubs: "main",
      Shoes: "shoes",
    },
    chef: {
      Top: "main",
      Detail: "second",
      Shirt: "#a096a0",
      Bottom: "pants",
      Shoes: "shoes",
    },
    player: {
      Top: "main",
      Apron: "second",
      Bottom: "pants",
      Shoes: "shoes",
    },
  },
  always: ["head_<kind>", "eyes", "brows"],
  hair: ["long", "bob", "bun", "curly", "crop", "ponytail", "braids"],
  accessories: {
    "1": "bow_<hair>",
    "2": "glasses",
    "3": "flower_<hair>",
  },
  tints: {
    Skin: "SKIN[look.skin].base (multiplies the face and body texture)",
    Hair: "HAIR[look.hair].base (multiplies the strand texture)",
    Brows: "HAIR[look.hair].dark",
    Eyes: "the iris colour (people.ts irisForSeed or IRIS); EyeWhite stays",
    Accessory: "OUTFIT[(look.outfit + 5) % 8]",
    fixed: ["EyeWhite", "EyeShine", "Lashes", "Sole", "Glasses", "Lens", "FlowerCentre"],
  },
  animations: [
    "cheer",
    "idle",
    "sit_chair",
    "sit_pedicure",
    "sit_sofa",
    "sit_stool",
    "sleepy",
    "talk",
    "walk",
    "wave",
    "work",
  ],
  clipSeconds: {
    walk: 1.333,
    idle: 3.0,
    talk: 2.667,
    sit_sofa: 3.0,
    sit_stool: 3.0,
    sit_chair: 3.0,
    sit_pedicure: 3.0,
    sleepy: 5.333,
    work: 2.0,
    wave: 1.333,
    cheer: 1.0,
  },
  seatedClips: ["sit_chair", "sit_sofa", "sit_stool", "sit_pedicure", "sleepy"],
  tris: {
    fem: {
      outfit_dress: 6851,
      outfit_jumper: 6213,
      outfit_dungarees: 6313,
      outfit_suit: 5947,
      outfit_hoodie: 7021,
      outfit_sporty: 6291,
      outfit_cardigan: 7235,
      outfit_jacket: 6159,
      outfit_scrubs: 5775,
      outfit_chef: 7077,
      outfit_player: 6661,
      head_fem: 2954,
      eyes: 784,
      brows: 652,
      hair_long: 2830,
      bow_long: 352,
      flower_long: 368,
      hair_bob: 2365,
      bow_bob: 352,
      flower_bob: 368,
      hair_bun: 2829,
      bow_bun: 352,
      flower_bun: 368,
      hair_curly: 1299,
      bow_curly: 352,
      flower_curly: 368,
      hair_crop: 830,
      bow_crop: 352,
      flower_crop: 368,
      hair_ponytail: 1722,
      bow_ponytail: 352,
      flower_ponytail: 368,
      hair_braids: 2266,
      bow_braids: 352,
      flower_braids: 368,
      glasses: 684,
    },
    masc: {
      outfit_jumper: 6375,
      outfit_dungarees: 6439,
      outfit_suit: 6097,
      outfit_hoodie: 7183,
      outfit_sporty: 6419,
      outfit_cardigan: 6321,
      outfit_jacket: 6289,
      outfit_scrubs: 5899,
      outfit_chef: 7231,
      outfit_player: 6827,
      head_masc: 2812,
      eyes: 784,
      brows: 500,
      hair_long: 2830,
      bow_long: 352,
      flower_long: 368,
      hair_bob: 2060,
      bow_bob: 352,
      flower_bob: 368,
      hair_bun: 2829,
      bow_bun: 352,
      flower_bun: 368,
      hair_curly: 1298,
      bow_curly: 352,
      flower_curly: 368,
      hair_crop: 2131,
      bow_crop: 352,
      flower_crop: 368,
      hair_ponytail: 1722,
      bow_ponytail: 352,
      flower_ponytail: 368,
      hair_braids: 2266,
      bow_braids: 352,
      flower_braids: 368,
      glasses: 684,
    },
  },
  hipsAboveFeet: {
    sit_sofa: 0.354,
    sit_stool: 0.38,
    sit_pedicure: 0.356,
    sleepy: 0.354,
  },
} as const

export const MODELS: ModelEntry[] = [
  {
    id: "brow-bar",
    name: "Brow bar chair",
    kind: "station",
    file: "stations/brow-bar-sunny.glb",
    footprint: [1.556, 1.212],
    height: 1.485,
    nodes: {
      seat: {
        pos: [-0.0017, 0.58, -0.1034],
        rotY: 0.0,
      },
      work: {
        pos: [0.5183, 0.0, -0.2034],
        rotY: -90.0,
      },
      tool: {
        pos: [0.6183, 0.6, -0.4534],
        rotY: 0.0,
      },
      lookat: {
        pos: [-0.0017, 1.236, -0.3744],
        rotY: 0.0,
      },
    },
    recolour: ["Accent", "Trim"],
    materials: ["Accent", "Accent2", "Base", "Bottlea", "Cream", "Glass", "Trim"],
    tris: 3200,
    styles: [
      {
        id: "sunny",
        name: "Sunny yellow",
        file: "stations/brow-bar-sunny.glb",
        thumb: "thumbs/brow-bar-sunny.png",
      },
      {
        id: "blush",
        name: "Blush",
        file: "stations/brow-bar-blush.glb",
        thumb: "thumbs/brow-bar-blush.png",
      },
      {
        id: "noir",
        name: "Noir and gold",
        file: "stations/brow-bar-noir.glb",
        thumb: "thumbs/brow-bar-noir.png",
      },
    ],
    sitClip: "sit_chair",
  },
  {
    id: "facial-chair",
    name: "Facial chair",
    kind: "station",
    file: "stations/facial-chair-rose.glb",
    footprint: [1.455, 1.444],
    height: 1.651,
    nodes: {
      seat: {
        pos: [-0.1011, 0.6, -0.0542],
        rotY: 0.0,
      },
      work: {
        pos: [0.4189, 0.0, -0.1742],
        rotY: -90.0,
      },
      tool: {
        pos: [0.5589, 0.66, -0.5542],
        rotY: 0.0,
      },
      lookat: {
        pos: [-0.1011, 1.256, -0.3252],
        rotY: 0.0,
      },
    },
    recolour: ["Accent", "Trim"],
    materials: ["Accent", "Base", "Bottlea", "Bottleb", "Bottlec", "Bottled", "Cream", "Glass", "Trim"],
    tris: 3200,
    styles: [
      {
        id: "rose",
        name: "Rose tufted",
        file: "stations/facial-chair-rose.glb",
        thumb: "thumbs/facial-chair-rose.png",
      },
      {
        id: "throne",
        name: "Gold throne",
        file: "stations/facial-chair-throne.glb",
        thumb: "thumbs/facial-chair-throne.png",
      },
      {
        id: "mint",
        name: "Minimal mint",
        file: "stations/facial-chair-mint.glb",
        thumb: "thumbs/facial-chair-mint.png",
      },
    ],
    sitClip: "sit_chair",
  },
  {
    id: "nail-desk",
    name: "Nail desk",
    kind: "station",
    file: "stations/nail-desk-marble.glb",
    footprint: [1.009, 0.875],
    height: 1.062,
    nodes: {
      seat: {
        pos: [0.0, 0.38, -0.2174],
        rotY: 0.0,
      },
      work: {
        pos: [0.0, 0.0, 0.7326],
        rotY: -180.0,
      },
      tool: {
        pos: [0.14, 0.643, 0.2026],
        rotY: 0.0,
      },
      lookat: {
        pos: [0.0, 1.108, -0.1474],
        rotY: 0.0,
      },
    },
    recolour: ["Accent", "Trim"],
    materials: ["Accent", "Accent2", "Base", "Bottlea", "Bottleb", "Bottlec", "Bottled", "Lamp", "Marble", "Trim"],
    tris: 3200,
    styles: [
      {
        id: "marble",
        name: "Marble and gold",
        file: "stations/nail-desk-marble.glb",
        thumb: "thumbs/nail-desk-marble.png",
      },
      {
        id: "pastel",
        name: "Pastel pink",
        file: "stations/nail-desk-pastel.glb",
        thumb: "thumbs/nail-desk-pastel.png",
      },
      {
        id: "wood",
        name: "Natural wood",
        file: "stations/nail-desk-wood.glb",
        thumb: "thumbs/nail-desk-wood.png",
      },
    ],
    sitClip: "sit_stool",
  },
  {
    id: "pedicure-chair",
    name: "Pedicure throne",
    kind: "station",
    file: "stations/pedicure-chair-lilac.glb",
    footprint: [1.109, 1.268],
    height: 1.275,
    nodes: {
      seat: {
        pos: [-0.0946, 0.426, -0.1325],
        rotY: 0.0,
      },
      feet: {
        pos: [-0.0946, 0.15, 0.3875],
        rotY: 0.0,
      },
      work: {
        pos: [-0.0946, 0.0, 0.8475],
        rotY: -180.0,
      },
      tool: {
        pos: [0.4254, 0.52, 0.3675],
        rotY: 0.0,
      },
      lookat: {
        pos: [-0.0946, 1.159, -0.1135],
        rotY: 0.0,
      },
    },
    recolour: ["Accent", "Trim"],
    materials: ["Accent", "Accent2", "Base", "Cream", "Trim", "Water"],
    tris: 3198,
    styles: [
      {
        id: "lilac",
        name: "Lilac throne",
        file: "stations/pedicure-chair-lilac.glb",
        thumb: "thumbs/pedicure-chair-lilac.png",
      },
      {
        id: "gold",
        name: "Royal gold",
        file: "stations/pedicure-chair-gold.glb",
        thumb: "thumbs/pedicure-chair-gold.png",
      },
      {
        id: "spa",
        name: "Teal spa",
        file: "stations/pedicure-chair-spa.glb",
        thumb: "thumbs/pedicure-chair-spa.png",
      },
    ],
    sitClip: "sit_pedicure",
  },
]

export const MODEL_BY_ID: Record<string, ModelEntry> = Object.fromEntries(MODELS.map(m => [m.id, m]))
