/**
 * The 3D models' catalogue, generated by assets-src/catalog_gen.py from the Blender builds (do not edit by hand:
 * change the build or the generator, then run `python assets-src/catalog_gen.py`). The floor engine reads models
 * only through here, so it never guesses a file, a node or a material name. See docs/3D-ASSETS.md.
 *
 * Every file is glTF 2.0 binary under public/models/, Y up, metres, +Z the model's front, the origin on the floor in
 * the middle of the footprint, compressed with meshopt (gltfpack): load with GLTFLoader.setMeshoptDecoder.
 * Materials are flat PBR colours named by role; soft ambient occlusion is baked into the vertex colours (COLOR_0), so
 * keep `vertexColors` on when you tint (`material.color` multiplies it).
 */

/** A helper node in a model: where a seated person's hips go (and which way they face: the node's +Z), etc. */
export type NodeInfo = { pos: [number, number, number]; rotY: number }

/** One look of a purchasable item: its own file, or the default file with materials recoloured. */
export type ModelStyle = { id: string; name: string; file: string; materialOverrides?: Record<string, number>; thumb: string }

export type ModelKind = 'station' | 'front' | 'room' | 'plant' | 'life' | 'decor' | 'gift'

export type ModelEntry = {
  id: string
  name: string
  kind: ModelKind
  /** The default style's file, relative to public/models/. */
  file: string
  /** Width (x) and depth (z) in metres. */
  footprint: [number, number]
  height: number
  /** Helper nodes by name: seat, work, feet, tool, lookat (stations), and any others the item has. */
  nodes: Record<string, NodeInfo>
  /** Materials a decor set may tint (Accent, Trim). */
  recolour: string[]
  materials: string[]
  tris: number
  /** The clip a person plays on this item's seat node, if it has one. */
  sitClip?: string
  /** Animation clips inside the file (the cat). */
  animations?: string[]
  /** For purchasable items: three styles (the first is the default). */
  styles?: ModelStyle[]
  /** The decor set or regular this item belongs to. */
  set?: string
  regular?: string
}

/**
 * The people: two bodies (fem, masc) on one 23-bone rig (Quaternius UAL naming), built on Quaternius' Universal Base
 * Characters (CC0). Each file holds every part: always show `always` (the head with its textured face, the eyes, the
 * brows), then one outfit mesh `outfit_<outfit>` (the body below the neck, dressed), one hair `hair_<style>` and at most
 * one accessory; hide the rest. Toggle `visible` on the part's named node (a child of the rig): its meshes, one per
 * material, hang under it, sometimes in an unnamed group.
 * - Tint by material name (`tints`): Skin, Hair and Brows multiply their textures; the outfit's materials follow
 *   people.ts `outfitOf` as `outfitTints` lists ('main', 'second', 'pants', 'shoes', a fixed colour, or 'main+' for a
 *   lighter main). Keep `vertexColors` on (the hair's soft occlusion is in COLOR_0).
 * - Hair: `hair[look.hairStyle]`. Accessories by Look.accessory: 1 bow, 2 glasses, 3 flower clip; `<hair>` is the
 *   hair style's name (each bow and flower sits on its own hair style's surface).
 * - Faces are Quaternius' sculpted faces (in the Skin texture on head_<kind>), with bigger, opened eyes. A customer's
 *   face differs by skin tone, eye colour (the Eyes material) and brow colour.
 * - Clips: `animations`. The seated ones (`seatedClips`) put the hips (pelvis joint) exactly on the model's origin,
 *   facing +Z: put the character's origin on a station's `seat` node with the node's rotation. For a seat with no
 *   node, `hipsAboveFeet` says how high the hips sit above the floor the feet rest on.
 * - `walkSpeed` is the ground speed (m/s) the in-place walk cycle matches at timeScale 1.
 */

export const PEOPLE = {
  files: {
    fem: "people/fem.glb",
    masc: "people/masc.glb",
  },
  bones: [
    "root",
    "pelvis",
    "spine_01",
    "spine_02",
    "spine_03",
    "neck_01",
    "Head",
    "clavicle_l",
    "upperarm_l",
    "lowerarm_l",
    "hand_l",
    "clavicle_r",
    "upperarm_r",
    "lowerarm_r",
    "hand_r",
    "thigh_l",
    "calf_l",
    "foot_l",
    "ball_l",
    "thigh_r",
    "calf_r",
    "foot_r",
    "ball_r",
  ],
  height: {
    fem: 1.93,
    masc: 1.947,
  },
  walkSpeed: {
    fem: 0.786,
    masc: 0.822,
  },
  outfits: {
    fem: [
      "cardigan",
      "chef",
      "dress",
      "dungarees",
      "hoodie",
      "jacket",
      "jumper",
      "player",
      "scrubs",
      "sporty",
      "suit",
    ],
    masc: ["cardigan", "chef", "dungarees", "hoodie", "jacket", "jumper", "player", "scrubs", "sporty", "suit"],
  },
  outfitTints: {
    dress: {
      Top: "main",
      Detail: "second",
      Shoes: "shoes",
    },
    jumper: {
      Top: "main",
      Bottom: "pants",
      Shoes: "shoes",
    },
    dungarees: {
      Top: "main",
      Bottom: "pants",
      Detail: "#f3d27a",
      Shoes: "shoes",
    },
    suit: {
      Top: "main",
      Bottom: "pants",
      Shirt: "#fbf8f6",
      Detail: "second",
      Shoes: "shoes",
    },
    hoodie: {
      Top: "main",
      Bottom: "pants",
      Shirt: "#ffffff",
      Shoes: "shoes",
    },
    sporty: {
      Top: "main",
      Bottom: "pants",
      Detail: "second",
      Shoes: "shoes",
    },
    cardigan: {
      Top: "main",
      Shirt: "second",
      Bottom: "pants",
      Detail: "main+",
      Shoes: "shoes",
    },
    jacket: {
      Top: "main",
      Shirt: "second",
      Bottom: "pants",
      Shoes: "shoes",
    },
    scrubs: {
      Scrubs: "main",
      Shoes: "shoes",
    },
    chef: {
      Top: "main",
      Detail: "second",
      Shirt: "#a096a0",
      Bottom: "pants",
      Shoes: "shoes",
    },
    player: {
      Top: "main",
      Apron: "second",
      Bottom: "pants",
      Shoes: "shoes",
    },
  },
  always: ["head_<kind>", "eyes", "brows"],
  hair: ["long", "bob", "bun", "curly", "crop", "ponytail", "braids"],
  accessories: {
    "1": "bow_<hair>",
    "2": "glasses",
    "3": "flower_<hair>",
  },
  tints: {
    Skin: "SKIN[look.skin].base (multiplies the face and body texture)",
    Hair: "HAIR[look.hair].base (multiplies the strand texture)",
    Brows: "HAIR[look.hair].dark",
    Eyes: "the iris colour (people.ts irisForSeed or IRIS); EyeWhite stays",
    Accessory: "OUTFIT[(look.outfit + 5) % 8]",
    fixed: ["EyeWhite", "EyeShine", "Lashes", "Sole", "Glasses", "Lens", "FlowerCentre"],
  },
  animations: [
    "cheer",
    "idle",
    "sit_chair",
    "sit_pedicure",
    "sit_sofa",
    "sit_stool",
    "sleepy",
    "talk",
    "walk",
    "wave",
    "work",
  ],
  clipSeconds: {
    walk: 1.333,
    idle: 3.0,
    talk: 2.667,
    sit_sofa: 3.0,
    sit_stool: 3.0,
    sit_chair: 3.0,
    sit_pedicure: 3.0,
    sleepy: 5.333,
    work: 2.0,
    wave: 1.333,
    cheer: 1.0,
  },
  seatedClips: ["sit_chair", "sit_sofa", "sit_stool", "sit_pedicure", "sleepy"],
  tris: {
    fem: {
      outfit_dress: 6829,
      outfit_jumper: 6195,
      outfit_dungarees: 6299,
      outfit_suit: 5913,
      outfit_hoodie: 7003,
      outfit_sporty: 6239,
      outfit_cardigan: 7167,
      outfit_jacket: 6111,
      outfit_scrubs: 5751,
      outfit_chef: 7057,
      outfit_player: 6651,
      head_fem: 2954,
      eyes: 784,
      brows: 652,
      hair_long: 2830,
      bow_long: 352,
      flower_long: 368,
      hair_bob: 2365,
      bow_bob: 352,
      flower_bob: 368,
      hair_bun: 2829,
      bow_bun: 352,
      flower_bun: 368,
      hair_curly: 1298,
      bow_curly: 352,
      flower_curly: 368,
      hair_crop: 830,
      bow_crop: 352,
      flower_crop: 368,
      hair_ponytail: 1720,
      bow_ponytail: 352,
      flower_ponytail: 368,
      hair_braids: 2266,
      bow_braids: 352,
      flower_braids: 368,
      glasses: 684,
    },
    masc: {
      outfit_jumper: 6376,
      outfit_dungarees: 6452,
      outfit_suit: 6108,
      outfit_hoodie: 7184,
      outfit_sporty: 6428,
      outfit_cardigan: 6346,
      outfit_jacket: 6314,
      outfit_scrubs: 5906,
      outfit_chef: 7220,
      outfit_player: 6828,
      head_masc: 2812,
      eyes: 784,
      brows: 500,
      hair_long: 2830,
      bow_long: 352,
      flower_long: 368,
      hair_bob: 2060,
      bow_bob: 352,
      flower_bob: 368,
      hair_bun: 2829,
      bow_bun: 352,
      flower_bun: 368,
      hair_curly: 1298,
      bow_curly: 352,
      flower_curly: 368,
      hair_crop: 2131,
      bow_crop: 352,
      flower_crop: 368,
      hair_ponytail: 1722,
      bow_ponytail: 352,
      flower_ponytail: 368,
      hair_braids: 2266,
      bow_braids: 352,
      flower_braids: 368,
      glasses: 684,
    },
  },
  hipsAboveFeet: {
    sit_sofa: 0.408,
    sit_stool: 0.44,
    sit_pedicure: 0.413,
    sleepy: 0.408,
  },
} as const

export const MODELS: ModelEntry[] = []

export const MODEL_BY_ID: Record<string, ModelEntry> = Object.fromEntries(MODELS.map(m => [m.id, m]))
